name: OpenSSF Scorecards

on:
  push:
    branches: [main, stage, dev]
  pull_request:
    branches: [main, stage]

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  scorecards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run Scorecards analysis
        uses: ossf/scorecard-action@v2.1.2
        with:
          results_format: 'sarif'
          publish_results: true

      - name: Upload Scorecards results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
