name: OpenSSF Scorecards

on:
  schedule:
    - cron: '30 1 * * 0' 
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  analyze:
    name: Run OpenSSF Scorecard
    runs-on: ubuntu-latest
    steps:
      - name: Scorecard analysis
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif

      - name: Upload Scorecards result to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
