name: OpenSSF Scorecard analysis

on:
  branch_protection_rule:
  schedule:
    - cron: '0 12 * * 5'   
  workflow_dispatch:       

permissions:
  contents: read
  security-events: write

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@6f04b51672b63f1f7cbb95e7f33423a4e0cd8c23 

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@e38b08c9e3b4ebd7e784685c7a1e5b0d251cc7a2  
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@b9b7cdd2c4f81cc972f5f48bb55c2a8f1e484ddc 
        with:
          sarif_file: results.sarif
