name: scorecards

on:
  pull_request:
    branches: [main, stage]
  push:
    branches: [main, stage]

permissions:
  contents: read

jobs:
  scorecards:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
      security-events: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Scorecards analysis
        uses: ossf/scorecard-action@v2.1.2
        with:
          results_format: sarif
          publish_results: true
