name: OpenSSF Scorecard

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  scorecards:
    runs-on: ubuntu-latest
    timeout-minutes: 3  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 

      - name: Run Scorecards analysis
        uses: ossf/scorecard-action@v2.1.2
        with:
          results_format: sarif
          results_file: results.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Scorecards analysis
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
